### ISSUE TITLE
storybook: add missing storybook components

### ISSUE THREAD

**Issue by toni-santos** [NIAEFEUP/website-niaefeup-frontend#101]
There are components that do not have a storybook implementation, this issue will help us define how to structure our storybook stories as well as provide us with well documented components.

- [ ] Components should have a story, when adequate
- [ ] Stories should adequately illustrate a component's different usages

**Comment by toni-santos** [comment]
Regarding this issue there are some considerations that I've found when trying to implement this myself in another issue.
- CSS files must be added to storybook's configuration, tailwind classes seem to work flawlessly.
- Static directories must also be added to the configuration
- There are some issues when rendering elements with CSS `position: fixed`

**Comment by BrunoRosendo** [comment]
I'm trying to use storybook for #108 and #8 but I keep encountering errors like this one:
```
[vite] Internal server error: Failed to resolve import "$lib/component/Icon.svelte" from "src/lib/notifications/Snackbar.svelte". Does the file exist?
```

This is different from the problems you report. Do you have any idea why this happens?

**Comment by toni-santos** [comment]
> I'm trying to use storybook for #108 and #8 but I keep encountering errors like this one:
> 
> ```
> [vite] Internal server error: Failed to resolve import "$lib/component/Icon.svelte" from "src/lib/notifications/Snackbar.svelte". Does the file exist?
> ```
> 
> This is different from the problems you report. Do you have any idea why this happens?

I believe I did come across a similar issue. From what I recall, of my vague research on this, it's related to the arguments needed for that specific component, although I could be wrong/misremembering. Regardless, `Icon.svelte` receives an Icon as one of its props, so **maybe** vite/storybook might not be able to find the place where we are getting these icons from, `src/lib/component/Icons.ts`, and hence thinking the component is malformed/doesn't exist; this seems like a stretch however :(.

**Comment by BrunoRosendo** [comment]
> > I'm trying to use storybook for #108 and #8 but I keep encountering errors like this one:
> > ```
> > [vite] Internal server error: Failed to resolve import "$lib/component/Icon.svelte" from "src/lib/notifications/Snackbar.svelte". Does the file exist?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is different from the problems you report. Do you have any idea why this happens?
> 
> I believe I did come across a similar issue. From what I recall, of my vague research on this, it's related to the arguments needed for that specific component, although I could be wrong/misremembering. Regardless, `Icon.svelte` receives an Icon as one of its props, so **maybe** vite/storybook might not be able to find the place where we are getting these icons from, `src/lib/component/Icons.ts`, and hence thinking the component is malformed/doesn't exist; this seems like a stretch however :(.

I managed to fix it by upgrading storybook. It previously didn't support sveltekit alias like `$lib`

**Comment by BrunoRosendo** [comment]
Regarding the styles not being applied, this could probably help https://stackoverflow.com/questions/68020712/tailwind-css-classes-not-showing-in-storybook-build
